on: [push, pull_request]
name: Formatting on nightly toolchain
jobs:
  format:
    runs-on: ubuntu-latest
    env:
      CARGO_UNSTABLE_SPARSE_REGISTRY: true
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@nightly
        with:
          components: rustfmt

      - name: Check formatting
        run: cargo fmt --verbose -- --check --verbose
      - name: Check formatting on fuzzing
        run: cargo fmt --verbose --manifest-path fuzz/Cargo.toml -- --check --verbose
