on: [push, pull_request]
name: Build fuzz targets on nightly toolchain
jobs:
  build_fuzzing:
    runs-on: ubuntu-latest
    env:
      RUSTFLAGS: "-D warnings"
      CARGO_UNSTABLE_SPARSE_REGISTRY: true
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@nightly
      - name: Install cargo fuzz
        run: cargo install cargo-fuzz --verbose
      - name: Build fuzz targets
        run: cargo fuzz build --verbose
