on: [push, pull_request]
name: Lints on stable toolchain
jobs:
  clippy:
    runs-on: ubuntu-latest
    env:
      RUSTFLAGS: "-D warnings"
      CARGO_UNSTABLE_SPARSE_REGISTRY: true
    steps:
      - uses: actions/checkout@v3
      - uses: dtolnay/rust-toolchain@stable
        with:
          components: clippy

      - name: Check Clippy lints
        run: cargo clippy --verbose --all-features -- -W clippy::match-same-arms
      - name: Check Clippy lints on tests
        run: cargo clippy --verbose --all-features --tests -- -W clippy::match-same-arms
      - name: Check Clippy lints on fuzzing
        run: cargo clippy --verbose --all-features --manifest-path fuzz/Cargo.toml -- -W clippy::match-same-arms
