on: [push, pull_request]
name: SemVer compatibility
jobs:
  semver:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Check semver
        uses: obi1kenobi/cargo-semver-checks-action@v1
